version: '3.4'

services:
  products:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80/http"

  customers:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80/http"


  orders:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80/http"


  search:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__Products=http://10.0.0.4:19081/ecommercescotnotis/products/
      - Services__Customers=http://10.0.0.4:19081/ecommercescotnotis/customers/
      - Services__Orders=http://10.0.0.4:19081/ecommercescotnotis/orders/
    ports:
      - "6004:80"

